package irc

const (
	Ping    = "PING"
	Nick    = "NICK"
	Join    = "JOIN"
	Part    = "PART"
	Mode    = "MODE"
	Privmsg = "PRIVMSG"
	Notice  = "NOTICE"
	Topic   = "TOPIC"
	Quit    = "QUIT"

	ReplyWelcome       = "001"
	ReplyYourHost      = "002"
	ReplyCreated       = "003"
	ReplyLUserClient   = "251"
	ReplyLUserOp       = "252"
	ReplyLUserUnknown  = "253"
	ReplyLUserChannels = "254"
	ReplyLUserMe       = "255"
	ReplyAway          = "301"
	ReplyWhoisUser     = "311"
	ReplyWhoisServer   = "312"
	ReplyWhoisOperator = "313"
	ReplyWhoisIdle     = "317"
	ReplyEndOfWhois    = "318"
	ReplyWhoisChannels = "319"
	ReplyNoTopic       = "331"
	ReplyTopic         = "332"
	ReplyNamReply      = "353"
	ReplyEndOfNames    = "366"
	ReplyMotd          = "372"
	ReplyMotdStart     = "375"
	ReplyEndOfMotd     = "376"
	ErrNicknameInUse   = "433"
)
